name: ltunes
description: An advanced music player for Android and iOS, built with Flutter.
publish_to: "none"
version: 2025.12.16+1
repository: https://github.com/laganyt/ltunes-flutter

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_service: ^0.18.18
  http: ^1.5.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  dart_tags: ^0.4.1
  audio_metadata_reader: ^1.4.2
  file_picker: ^10.3.3
  path: ^1.9.1
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  just_audio: ^0.10.5
  resumable_downloader: ^0.0.37
  palette_generator: ^0.3.3+7
  scrollable_positioned_list: ^0.3.8
  cached_network_image: ^3.4.1
  wakelock_plus: ^1.4.0
  audio_session: ^0.2.2
  flutter_local_notifications: ^19.5.0
  fl_chart: ^1.1.1
  syncfusion_flutter_xlsio: ^31.2.4
  excel:
    path: excel
  flutter_slidable: ^4.0.3
  share_plus: ^12.0.1
  haptic_feedback: ^0.6.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - ./assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "./assets/icon/icon.png"
  adaptive_icon_background: "#333333"
  adaptive_icon_foreground: "./assets/icon/icon.png"
